### ISSUE TITLE
Re-use JS runtime for multiple requests

### ISSUE THREAD

**Issue by theduke** [wasmerio/winterjs#1]
Currently a new JS runtime is initialized per request.

We need to use a single runtime to process requests in parallel.

Easy way to do it:

* send incoming hyper requests through a channel, together a oneshot channel for sending back the response
* main loop receives requests and invokes the JS handler
* keep a map of requests with associated request id (type is already present in `fetch`)
* send response to the oneshot channel when the JS promise finishes

**Comment by Arshia001** [comment]
But won't running multiple functions on the same runtime lead to stuff like static variables not being cleaned up between function invocations etc.? Are we sure we want to create that kind of error scenario for the users?

**Comment by syrusakbary** [comment]
Extra information (reused proc macro?):
https://github.com/Redfire75369/spiderfire/tree/master

**Comment by theduke** [comment]
>  Are we sure we want to create that kind of error scenario for the users?

The performance difference will be huge. 
I think this should be expected, it's how regular servers behave.
