### ISSUE TITLE
Make clear that WinterJS is not endorsed by WinterCG officially

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/winterjs#14]
Some people related to WinterCG mentioned that it would be useful to make clear that WinterJS is not connected to WinterCG in any official way.

See tweet: https://x.com/jasnell/status/1718284542619054277?s=46

Some people suggested renaming the project.
Regarding that, two names appear as alternatives: Snow and Ice, but both names are actively used by related JS projects:
* https://github.com/LavaMoat/snow
* https://github.com/alibaba/ice

If we find a suitable alternative name for the project, it may be worth renaming it (please post a suggestion here if you would like us to consider it).

In any case should make clear that WinterJS is not endorsed officially by WinterCG.

**Comment by JoviDeCroock** [comment]
A few that popped to mind

- blizzard
- frigid
- glacial
