### ISSUE TITLE
Missing `Headers.entries`

### ISSUE THREAD

**Issue by pi0** [wasmerio/winterjs#25]
(context: from unjs/nitro#1861 tracker)

---

Tested runtime version: v0.1.7

MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries

`Headers.entries` method seems missing.

**Comment by Arshia001** [comment]
According to https://fetch.spec.whatwg.org/#headers, the headers object itself should be iterable. There is no `entries` method in the standard AFAICT.

**Comment by syrusakbary** [comment]
I've checked in Deno Deploy and Cloudflare Workers with this script:

```js
self.addEventListener('fetch', event => {
  let headers = event.request.headers;
  event.respondWith(new Response(`typeof headers.entries == "${typeof headers.entries}"`));
})
```

In both cases, the response was:
```
typeof headers.entries == "function"
```

Which means that both Cloudflare Workers and Deno Deploy had this implemented. We should follow up to see if it should be in the spec

**Comment by syrusakbary** [comment]
We made the decision to follow Cloudflare Workers, and implement `Headers.entries`

**Comment by pi0** [comment]
Thanks!
