### ISSUE TITLE
Missing `URL.pathname`

### ISSUE THREAD

**Issue by pi0** [wasmerio/winterjs#26]
(context: from unjs/nitro#1861 tracker)

---

Tested runtime version: v0.1.7

MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname

`URL.pathname` property is not available (but `.path` is which I'm not sure is standard at least in other runtimes)

**Comment by Arshia001** [comment]
Fixed in 0.1.8.

**Comment by pi0** [comment]
Thanks!

**Comment by ghostdevv** [comment]
Hey @Arshia001 it wasn't working for me in 0.19.0

**Comment by Arshia001** [comment]
@ghostdevv thanks for reporting this, it's a regression and should be fixed again with the next release.
