### ISSUE TITLE
Cannot construct URL with base

### ISSUE THREAD

**Issue by pi0** [wasmerio/winterjs#27]
(context: from unjs/nitro#1861 tracker)

---

Tested runtime version: v0.1.7

MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#base

Event when providing a URL base, runtime errors with base missing. E.g: `new URL('./foo, 'http://example.com')`

**Comment by Arshia001** [comment]
Fixed in 0.1.8.

**Comment by pi0** [comment]
Thanks!
