### ISSUE TITLE
Checking/compilation fails in debug mode

### ISSUE THREAD

**Issue by theduke** [wasmerio/winterjs#32]
`cargo check` / `cargo build` do not currently fails for me with:

```
  /nix/store/x8lqlydsxbrwvf6p7v18gws8kn1xl37f-glibc-2.38-23-dev/include/features.h:414:4: error: _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror,-W#warnings]
```

This only occurs in debug builds. `cargo {check,build} --release` works fine.

**Comment by Arshia001** [comment]
@theduke is this on a native build or WASIX? I'm making debug builds all the time, and it's working fine with my toolchain.
