### ISSUE TITLE
Wasmer Winter server hangs when calling fetch tests

### ISSUE THREAD

**Issue by dynamite-bud** [wasmerio/winterjs#34]
## Description

The `wasmer-winter` server hangs when calling fetch tests.

#### Start the local server

```console
wasmer run wasmer-tests/winter-fetch-tests --net --env PORT=3000
```

The above will start a server for serving the fetch requests

#### Running the fetch tests server

You need to start a `wasmer/winterjs` server using the following [11-fetch.js](https://github.com/wasmerio/winterjs/blob/main/test-suite/js-test-app/src/test-files/11-fetch.js) file.

Please place an event listener at the end of this file:
```js
addEventListener("fetch", (fetchEvent) => {
  fetchEvent.respondWith(handleRequest(fetchEvent.request));
});
```

```console
wasmer run wasmer/winterjs --net --mapdir /tests:. -- /tests/11-fetch.js --watch
```
The above will start a server on `127.0.0.1:8080`. When making a cURL request to the server.

```console
curl 127.0.0.1:8080
```

The above server goes in a wait state and doesn't return a response for a long time.

**Comment by Arshia001** [comment]
@dynamite-bud this should be fixed in 0.1.10. Can you verify please?
