### ISSUE TITLE
JavaScript failed with "Script error: the fetch event handler should not return a value", but there is no return value indeed

### ISSUE THREAD

**Issue by hikerpig** [wasmerio/winterjs#37]
Here is a test example:

```js
addEventListener("fetch", async (event) => {
  const requestText = await event.request.text();
  event.respondWith(new Response('test'));
});

```

Start with winterjs:
```
wasmer run wasmer/winterjs --net --mapdir=tests:tests tests/test.js
```

Send a POST request to `127.0.0.1:8080` and strange error shown:

```
INFO wasmer_winter::server: starting server on '127.0.0.1:8080' listen=127.0.0.1:8080
ERROR wasmer_winter::server: could not process request error="Error {\n    context: \"JavaScript failed\",\n    source: \"Script error: the fetch event handler should not return a value\",\n}"
```

**Comment by hikerpig** [comment]
Well it may has something to do with `async` , maybe JS engine treats it with a `Promise` as return value.

So I changed the test script to:

```js
addEventListener("fetch", (event) => {
  event.request.text().then((requestText) => {
    const res = new Response('test')
    event.respondWith(res);
  })
});
```
But there goes another error.  Currently I can't find a way to run async handing in fetch event handler.

> ERROR winterjs::server: could not process request error="Error {\n    context: \"JavaScript failed\",\n    source: \"Script error: FetchEvent.respondWith must be called with a Response object before returning\",\n}"

**Comment by Arshia001** [comment]
Hi @hikerpig!

You're indeed seeing the error because an `async function` always returns a promise. The correct way to do async work is to call `event.RespondWith` with a promise that resolves to a `Response`, like so:

```js
async function handleRequest(req) {
  return new Response('hello!');
}

addEventListener('fetch', event => event.respondWith(handleRequest(event.req)));
```
