### ISSUE TITLE
Missing tag for 1.0

### ISSUE THREAD

**Issue by darix** [wasmerio/winterjs#53]
this blog post https://wasmer.io/posts/winterjs-v1 announces 1.0 but i do not see a tag/release for it?

**Comment by Arshia001** [comment]
The release you're looking for is here: https://wasmer.io/wasmer/winterjs

We don't provide native builds of WinterJS yet.

**Comment by Arshia001** [comment]
Actually, I just realized I hadn't pushed the 1.0.0 version bump... thanks for reporting this, @darix !

**Comment by darix** [comment]
thank you. makes it easier for packagers to pick it up.

**Comment by darix** [comment]
https://github.com/wasmerio/winterjs/tags still doesnt show 1.0.0 btw

**Comment by Arshia001** [comment]
Right, we don't exactly have much in the form of CI/CD and releases are still manual. To be fixed before the next release.

I was referring to 0bf0331 when I said I'd forgotten to push the 1.0 version bump. I'll also create a tag manually this time.
