### ISSUE TITLE
Implement URL Class

### ISSUE THREAD

**Issue by theduke** [wasmerio/winterjs#6]
The spec uses the `URL` class in multiple places for requests/responses.

Need to add that class and use it in all required places. (request/response class fields, support for supplying a URL as first fetch param, etc).

Two ways to go: use a Rust class, or just use one of the available Javascript polyfills and add them to the `setup.js` code.

**Comment by Arshia001** [comment]
@theduke the first parameter to `fetch` should be either a string or anything with a stringifier(?), so the rust side is probably OK. We'll want to add that functionality for use by the function JS code though.

**Comment by nicolo-ribaudo** [comment]
You might be interested in https://github.com/servo/rust-url, which is runs WPT tests to ensure spec compliance.

**Comment by theduke** [comment]
@Arshia001 I think this is actually already done now, through Spiderfire?
