### ISSUE TITLE
Unable to install winterjs on Windows

### ISSUE THREAD

**Issue by kaiser101** [wasmerio/winterjs#68]
I am running Windows 10, build 19045.4170. I tried installing winterjs using cargo, but get the following error.

    Updating git repository `https://github.com/wasmerio/winterjs`
  Installing winterjs v1.1.0 (https://github.com/wasmerio/winterjs#6cee3096)
    Updating git repository `https://github.com/wasix-org/h2.git`
    Updating git repository `https://github.com/wasix-org/hyper`
    Updating git repository `https://github.com/wasix-org/hyper-rustls.git`
    Updating git repository `https://github.com/wasix-org/libc.git`
    Updating git repository `https://github.com/wasix-org/mio.git`
    Updating git repository `https://github.com/wasix-org/rustls.git`
    Updating git repository `https://github.com/wasix-org/socket2.git`
    Updating git repository `https://github.com/wasix-org/tokio.git`
    Updating crates.io index
    Updating git repository `https://github.com/wasmerio/spiderfire.git`
    Updating git repository `https://github.com/wasmerio/mozjs.git`
    Updating git repository `https://github.com/wasix-org/static-web-server`
    Updating git repository `https://github.com/wasix-org/rustls-native-certs.git`
    Updating git repository `https://github.com/wasix-org/tokio-rustls.git`
    Updating git repository `https://github.com/wasix-org/ring.git`
    Updating git repository `https://github.com/wasix-org/sct.git`
    Updating git repository `https://github.com/wasix-org/webpki.git`
    Updating git repository `https://github.com/wasix-org/libc.git`
    Updating git repository `https://github.com/wasix-org/signal-hook.git`
    Updating git repository `https://github.com/wasix-org/webpki-roots.git`
  Downloaded cc v1.0.92
  Downloaded getrandom v0.2.14
  Downloaded serde_repr v0.1.19
  Downloaded swc_core v0.90.30
  Downloaded swc_visit v0.5.12
  Downloaded 5 crates (138.7 KB) in 4.62s
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.197
   Compiling autocfg v1.2.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling windows_x86_64_gnu v0.52.4
   Compiling cc v1.0.92
   Compiling getrandom v0.2.14
   Compiling pin-project-lite v0.2.14
   Compiling itoa v1.0.11
   Compiling memchr v2.7.2
   Compiling windows_x86_64_gnu v0.48.5
   Compiling quote v1.0.35
   Compiling syn v2.0.58
   Compiling aho-corasick v1.1.3
   Compiling regex-syntax v0.8.3
   Compiling once_cell v1.19.0
   Compiling windows-targets v0.48.5
   Compiling regex-automata v0.4.6
   Compiling lazy_static v1.4.0
   Compiling winapi v0.3.9
   Compiling hashbrown v0.14.3
   Compiling swc_macros_common v0.3.9
   Compiling regex v1.10.4
   Compiling tracing-core v0.1.32
   Compiling typenum v1.17.0
   Compiling serde_derive v1.0.197
   Compiling tracing-attributes v0.1.27
   Compiling num-traits v0.2.18
   Compiling generic-array v0.14.7
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling percent-encoding v2.3.1
   Compiling tracing v0.1.40
   Compiling futures-core v0.3.30
   Compiling form_urlencoded v1.2.1
   Compiling windows-targets v0.52.4
   Compiling unicode-normalization v0.1.23
   Compiling windows-sys v0.48.0
   Compiling unicode-bidi v0.3.15
   Compiling siphasher v0.3.11
   Compiling fnv v1.0.7
   Compiling rand_core v0.6.4
   Compiling serde_json v1.0.115
   Compiling rand v0.8.5
   Compiling idna v0.5.0
   Compiling phf_shared v0.11.2
   Compiling ryu v1.0.17
   Compiling rustversion v1.0.15
   Compiling num_cpus v1.16.0
   Compiling unicode-width v0.1.11
   Compiling url v2.5.0
   Compiling phf_generator v0.11.2
   Compiling uuid v1.8.0
   Compiling either v1.10.0
   Compiling radium v0.7.0
   Compiling bytes v1.6.0
   Compiling libc v0.2.152 (https://github.com/wasix-org/libc.git?branch=v0.2.152#26f165f1)
   Compiling subtle v2.5.0
   Compiling debugid v0.8.0
   Compiling phf_macros v0.11.2
   Compiling windows-sys v0.52.0
   Compiling Inflector v0.11.4
   Compiling slab v0.4.9
   Compiling if_chain v1.0.2
   Compiling futures-sink v0.3.30
   Compiling outref v0.1.0
   Compiling anyhow v1.0.81
   Compiling glob v0.3.1
   Compiling data-encoding v2.5.0
   Compiling stable_deref_trait v1.2.0
   Compiling rustc-hash v1.1.0
   Compiling tap v1.0.1
   Compiling wyz v0.5.1
   Compiling triomphe v0.1.11
   Compiling clang-sys v1.7.0
   Compiling simd-abstraction v0.7.1
   Compiling phf v0.11.2
   Compiling num-bigint v0.4.4
   Compiling rustix v0.38.32
   Compiling new_debug_unreachable v1.0.6
   Compiling funty v2.0.0
   Compiling smallvec v1.13.2
   Compiling equivalent v1.0.1
   Compiling indexmap v2.2.6
   Compiling hstr v0.2.8
   Compiling bitvec v1.0.1
   Compiling errno v0.3.8
   Compiling base64-simd v0.7.0
   Compiling futures-channel v0.3.30
   Compiling swc_visit_macros v0.5.11
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling num-integer v0.1.46
   Compiling futures-macro v0.3.30
   Compiling winapi-util v0.1.6
   Compiling lock_api v0.4.11
   Compiling thiserror v1.0.58
   Compiling minimal-lexical v0.2.1
   Compiling scoped-tls v1.0.1
   Compiling pin-utils v0.1.0
   Compiling bitflags v2.5.0
   Compiling futures-io v0.3.30
   Compiling futures-task v0.3.30
   Compiling parking_lot_core v0.9.9
   Compiling unicode-id-start v1.1.2
   Compiling sourcemap v8.0.1
   Compiling futures-util v0.3.30
   Compiling swc_visit v0.5.12
   Compiling nom v7.1.3
   Compiling better_scoped_tls v0.1.1
   Compiling termcolor v1.4.1
   Compiling digest v0.10.7
   Compiling swc_atoms v0.6.6
   Compiling home v0.5.9
   Compiling http v0.2.12
   Compiling mio v0.8.9 (https://github.com/wasix-org/mio.git?branch=v0.8.9#f55de7d1)
   Compiling socket2 v0.5.5 (https://github.com/wasix-org/socket2.git?branch=v0.5.5#87e78d44)
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
    --> C:\Users\Administrator\.cargo\git\checkouts\socket2-e5824eb568832040\87e78d4\src\socket.rs:1125:65
     |
1125 |             getsockopt::<c_int>(self.as_raw(), sys::IPPROTO_IP, libc::IP_HDRINCL)
     |                                                                 ^^^^ use of undeclared crate or module `libc`

error[E0433]: failed to resolve: use of undeclared crate or module `libc`
    --> C:\Users\Administrator\.cargo\git\checkouts\socket2-e5824eb568832040\87e78d4\src\socket.rs:1155:17
     |
1155 |                 libc::IP_HDRINCL,
     |                 ^^^^ use of undeclared crate or module `libc`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `socket2` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `winterjs v1.1.0 (https://github.com/wasmerio/winterjs#6cee3096)`, intermediate artifacts can be found at `C:\Users\ADMINI~1\AppData\Local\Temp\cargo-installJKF2l4`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by Arshia001** [comment]
@kaiser101 Hi, thanks for reporting this issue!

We have not tried running WinterJS on Windows. It is geared towards WASIX, and it just so happens that WASIX is very close to POSIX which means WinterJS runs on Linux and macOS, but Windows is quite different and would require additional effort, which is not planned in the short term.
