### ISSUE TITLE
need primordials?

### ISSUE THREAD

**Issue by MasatoDev** [wasmerio/winterjs#78]
## Overview

Will primordials be introduced eventually, as mentioned in the code below?

https://github.com/wasmerio/winterjs/blob/main/src/builtins/internal_js_modules/node/async_hooks.ts#L7-L8

There was a discussion about this in the past at Deno.
I can see some opinions that do not support the following.

>I'd caution against relying on primordials for security.

https://github.com/denoland/deno/pull/10939

## Reference

https://github.com/nodejs/node/blob/main/doc/contributing/primordials.md

**Comment by Arshia001** [comment]
@MasatoDev the code in question was ported from the deno repository, and the comment is just a left-over. There is no plan to support primordials right now, unless there's a valid argument in favor of supporting them.

**Comment by MasatoDev** [comment]
I understand. Thank you for your reply!
