### ISSUE TITLE
invalid property name in regular expression

### ISSUE THREAD

**Issue by ayonli** [wasmerio/winterjs#80]
The following regular express failed to compile:

```js
const EMOJI_RE = /^(?:\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F)(?:\u200d(?:\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F))*$/u; 
```

The program reported a SyntaxError, saying that 'invalid property name in the regular expression'.

However, the regex works well in Firefox, as well as other browsers and runtimes.

**Comment by Arshia001** [comment]
Thanks for the issue report, @ayonli. This has been fixed in https://github.com/wasmerio/mozjs/commit/51b9e77762ae051d38675453a897d87f04810314 and https://github.com/wasmerio/mozjs/commit/a408521096a0f8530993fee6b5efebf9396d51be, and will be published as part of the next version (1.2.0).
