### ISSUE TITLE
Process control, multi-processing, mult-threading.

### ISSUE THREAD

**Issue by arreehm** [wasmerio/winterjs#82]
Greetings, 

Node have clusters that can be done with fork, socket IPC communication, so multiple processes are possible. And they can communicate...

What does winter offer to occupy more than one CPU core? I think workers as parallelizm(thread) and child with shared memory as another process spawned, would be another interesting thing.

If you want, I can make you a specification, for this multi-thing, so processes would share a buffer, has abillity to send signal, like urge for buffer read to another process by function execution, shared memory, that's readable from both processes, each process have copy on write for that, and then there is possibility to further merge it in code.

Also I know how to optimize execution speed even more, if you're interested.

Also, how do I set up `process.on("SIGTERM", ) hooks in winter? 

Do you have fs.watch? Maybe they would be good to write filesystem module, that would support having file opened all the time, and it would inform on change of file. So we could change settings in our applications, by editing file, without restarting server and such things.

Sockets and HTTP clients works? Also I would like some module, that does RAW access to socket, so I could like detect incoming ping.

Thank you. Any response appreciated.

**Comment by Arshia001** [comment]
Hi @arreehm!

WinterJS has built-in multi-threading support. You can configure the maximum number of threads that will be spawned via a cli switch (`--max-js-threads` IIRC).

As for `process.on`, `fs.watch` etc., WinterJS is mainly a WinterCG-compatible runtime, and WinterCG does not specify any of those. There is also a cloudflare mode which is *mostly* compatible with cloudflare (enough to run many popular frameworks), but it is not 100% compatible. Node.js compatibility is not planned at this point.
